### ISSUE TITLE
The original locations of vertices change at the first frame.

### ISSUE THREAD

**Issue by hooyuser** [taichi-dev/taichi_blend#5]
I use `nb.mesh_update()` to generate an animation. The `main()` function is basically like

```python
@nb.add_animation
def main():  
    for frame in range(1, 250):
        yield nb.mesh_update(mesh, x.to_numpy().reshape(vertex_num,3))   
        for step in range(substep_num):
            substep()
```

After playing the animation, I jump to frame 1 and expect all vertices return to their original positions as the built-in physical system of Blender does.

However, I find the original locations of vertices have changed at frame 1, while the mesh just keeps its initial shape at frame 0.

When `frame == 1`, `nb.mesh_update()` is called before any modifications for the mesh, but the mesh actually changes at frame 1. Why would this happen?

**Comment by hooyuser** [comment]
This blender file may help reproduce the result. [https://github.com/hooyuser/blender-file/blob/main/sdf%20collision.blend](url)

**Comment by archibate** [comment]
This is an expected feature that frame 0 and 1 are different.
Also note that we should use `for frame in range(250)` since currently taichi_blend starts from frame 0.

Here's the timetable:
yield
frame 0
yield
frame 1
yield
frame 2

So IIUC the blender built-in engine is:
yield
frame 0
frame 1
yield
frame 2
?
Thank for the information, I will have a try later when I have access to my computer.

**Comment by hooyuser** [comment]
Thanks for your detailed explanations! I know the built-in physics allows to manually assign the start frame of simulation，but I have no ideas how this works. 

Maybe I could close this issue. Super cool to see this project moving along.
