### ISSUE TITLE
Limit of particles about 3 million for gpu, after that Blender needs a restart

### ISSUE THREAD

**Issue by AnasFX** [taichi-dev/taichi_blend#8]
When I try to set the particles to over 3 million in the ( Make Meta Node ) on GPU back end it crashes.
Also when I change the ( Mpm Domain Node Res ) to 1024,1024,1024 the same crash happens.
The CPU back end goes to 8 millions without any problem.
GPU memory is not a limit here, cause the usage is less than 4 GB of VRam. 
Also after installed the add-on ( v0.0.6 ) version ( Taichi-Blend-win-37.zip ), it shows in the add-on info menu that it is ( 0.0.5 ).

Any thoughts ?

- Blender 2.91.0
- add-on ( v0.0.6 ) version ( Taichi-Blend-win-37.zip )  "Although it shows that it is 0.0.5, I don't know if this is a typo error in the add-on, or is it really 0.0.5"
- Water Solver

I hope it is easy to fix 🙁 
Best Regards

**Comment by archibate** [comment]
Hi, this might because Taichi will only pre-allocate 1 GB memory for CUDA by default. We may:
1. specify environment variables: `TI_DEVICE_MEMORY_GB=3.9` to pre-allocate 3.9 GB memory.
2. Use `ti.init(device_memory_gb=3.9)` in `Taichi-Blend/user_iface/engine.py` at line 8. I can help add an option in the menu to allow users to tweak it easily.

**Comment by AnasFX** [comment]
That did the trick 😁 . Thanks .

Just some notes that I noticed if you can clear it for me please: 
- Is there a way to change the properties of the fluid or the jelly.
- If not, then what are the properties that you have chosen to determine the water material and the jelly material .
- Is there a way to export the particles to external file, like the normal file format that Blender uses for storing simulation caches in a Sparse way. Because every time I do a simulation the Blender file in memory keeps getting bigger and bigger until it eats all the PC ram. The file reached 40 GB of ram until it crashes.
- I tried to use the ( Purge All ) option in the file menu, but it had no effect. 
- I tried to read the ( blender_nodes ) help in this link ( https://taichi-elements.readthedocs.io/en/latest/blender_nodes.html ), but I didn't find alot of the nodes in Blender 🙁 .

Any thoughts 
Thanks

**Comment by archibate** [comment]
> Is there a way to change the properties of the fluid or the jelly.
> If not, then what are the properties that you have chosen to determine the water material and the jelly material.

I've chosen E=1e6 and nu=0.2, the same value as Taichi-Elements did. The density (particles per grid) could also be a property of material.

> Is there a way to export the particles to external file, like the normal file format that Blender uses for storing simulation caches in a Sparse way. Because every time I do a simulation the Blender file in memory keeps getting bigger and bigger until it eats all the PC ram. The file reached 40 GB of ram until it crashes.

Good idea! I think we can add a node for disk cache. Note that 40 GB is likely the particle 3d position stored in float32: 3e6 / 1024 / 1024 * 3 * 4 = 34.33.

> I tried to read the ( blender_nodes ) help in this link ( https://taichi-elements.readthedocs.io/en/latest/blender_nodes.html ), but I didn't find alot of the nodes in Blender

This is because Taichi-Blend is a completely different project from Taichi-Elements.. But surely some of their features / nodes will be added in the future.

**Comment by AnasFX** [comment]
Thanks for the clearfication 👍 💯  .
Does that means that I need to use ( Taichi-Elements ) for the now ? Can I install both of them without having problems to any of them ?
Because from my understanding that ( Taichi_Blend ) also installs ( Taichi-Elements ) too, and I a am afraid that if I install both of them they will crash each other 🙁.
